WIP: porfolio site
quantacms/quanta pull request #169
Opened 2018-10-25 15:27 UTC by dongido001

This is the initial commit.

The block levels for components are not used for now. 

I'm still looking at how it works. I tried using it, but it broke the pages since it adds an extra `div`.

2018-10-26 09:15 UTC, Aldus83 requested changes
First round of CR

2018-10-26 09:15 UTC, gattoplano commented on profiles/portfolio/_components/header/tpl.html
> +        </ul>
Please use qtag_MENU - that will do the nav ul for you. 
It works either inline, with links separated by ---, or loading another node, with one link per line.
Example inline: 
[MENU|links={LINK:about}---{LINK:work}---{LINK:services}] (etc. etc.)

2018-10-26 09:15 UTC, gattoplano commented on profiles/portfolio/_components/header/tpl.html
> +<header class="header">
please use the [HEADER] qtag

2018-10-26 09:15 UTC, gattoplano commented on profiles/portfolio/assets/css/style.css
> +    display: grid;
Quanta integrates grid into qtags - so you don't have to reimplement it in css.
Please check the grid module:
https://github.com/quantacms/quanta/tree/master/engine/modules/core/grid

2018-10-26 09:15 UTC, gattoplano commented on profiles/portfolio/index.html
> +                </ul>
Please
1) create a _components/menu node 
2) inside menu node, use qtag_MENU for the links:
https://github.com/quantacms/quanta/blob/05659f285243a24cb91c781fc09abc6d86b114b4/engine/modules/core/menu/menu.qtags.inc#L19

2018-10-26 09:15 UTC, gattoplano commented on profiles/portfolio/index.html
> +        <header class="header">
Please use the header node you already created.
If you don't want the div added by qtag_BLOCK, you can use qtag_CONTENT i.e. 
[CONTENT:header]

2018-10-26 09:17 UTC, gattoplano commented
Thanks @dongido001,
great start. As HTML can be a starting points until you get used to qtags, we need to progressively get rid of about the whole HTML in favor of qTags, that is Quanta's core feature.

After we are done with the first change request, another will follow for adapting to grid, etc. 
Keep up the good work

A

2018-10-26 16:40 UTC, dongido001 commented on profiles/portfolio/index.html
> +        <header class="header">
ok, thanks.

2018-10-28 21:21 UTC, dongido001 commented on profiles/portfolio/_components/header/tpl.html
> +        </ul>
Updated

2018-10-29 19:25 UTC, Aldus83 requested changes

2018-10-29 19:25 UTC, gattoplano commented on profiles/portfolio/_components/header/tpl.html
> +        </h1>
Please use [TITLE] instead of "Your Favorite..." etc. 
The title will be gathered from the current node's json

2018-10-29 19:25 UTC, gattoplano commented on profiles/portfolio/_components/footer/tpl.html
> +    Mail to <a class="footer-link" href="mailto: 123.emailm@outlook.com"> info@123.xyz</a>
Use [EMAIL:123.email@outlook.com] 
We will then need to add the email as a json attribute that the end user can edit using  Shadow

2018-10-29 19:25 UTC, gattoplano commented on profiles/portfolio/_components/header/tpl.html
> +        <div>
use [TEASER] here ?

2018-10-30 17:27 UTC, dongido001 commented on profiles/portfolio/_components/footer/tpl.html
> +    Mail to <a class="footer-link" href="mailto: 123.emailm@outlook.com"> info@123.xyz</a>
How does shadow works? How can I edit

2018-10-30 17:28 UTC, dongido001 commented on profiles/portfolio/_components/header/tpl.html
> +        </h1>
Updated

2018-10-30 17:28 UTC, dongido001 commented on profiles/portfolio/_components/header/tpl.html
> +        <div>
Updated

2018-11-19 10:26 UTC, dongido001 commented
A lot has changed here. 

I will close this pull request and open a fresh one so it is easy to follow

2018-11-19 10:26 UTC, closed without merging