Fix/alfa 373 nodes saved language
quantacms/quanta pull request #325
Opened 2024-04-26 08:43 UTC by MohamedTaha880

2024-04-26 18:31 UTC, Aldus83 requested changes
just an amendment to not reimplement existing dir variables

2024-04-26 18:31 UTC, Aldus83 commented on src/modules/environment/hooks/environment.hook.inc
> +  $envFilePath= $_SERVER['DOCUMENT_ROOT']. '/sites/'.$host.'/.env';
You already should have this variable valorised by Quanta (I think it's called $env->dir['docroot']) no need to reimplement, better using standard variables

2024-05-03 07:52 UTC, MohamedTaha880 commented on src/modules/environment/hooks/environment.hook.inc
> +  $envFilePath= $_SERVER['DOCUMENT_ROOT']. '/sites/'.$host.'/.env';
@Aldus83 
Done

2024-05-07 11:21 UTC, Aldus83 commented
@MohamedTaha880  please resolve conflict, we need to merge this

2024-05-07 14:31 UTC, merged