Import file module
quantacms/quanta pull request #376
Opened 2024-06-07 06:41 UTC by MohamedTaha880

2024-06-07 20:55 UTC, Aldus83 requested changes

2024-06-07 20:55 UTC, Aldus83 commented on src/modules/form/classes/Qtags/FormItemFile.qtag.php
> +        $rendered = '<input type="hidden" name="tmp_upload_dir" value="[ATTRIBUTE|name=tmp_files_dir]" />' . '<div class="upload-files"><div class="drop">Drop here files<a>or press here</a><input typ
@MohamedTaha880  all this code is very redundant with line 28. Please optimise the code

2024-06-07 20:59 UTC, Aldus83 requested changes

2024-06-07 20:59 UTC, Aldus83 commented on src/modules/importfile/classes/Common/ImportFileFactory.class.php
> +class ImportFileFactory {
An ImportFileFactory is an overkill, you can use the existing FileFactory module and add methods as needed

2024-06-07 20:59 UTC, Aldus83 commented on src/modules/importfile/tpl/import_file_form.inc
> +[SHADOW_DESCRIPTION:[TEXT|tag=upload-logo:Upload yor logo]]
"logo" seems not related to this

2024-06-07 20:59 UTC, Aldus83 commented on src/modules/importfile/tpl/import_file_form.inc
> +    [INPUT|title=thumbnail|id=edit_thumbnail|type=hidden|name=edit-thumbnail|value={ATTRIBUTE|name=thumbnail|no_qtags}:metadata-form]
I am a bit confused by the use of thumbnail

2024-06-07 20:59 UTC, Aldus83 commented on src/modules/importfile/classes/Common/ImportFileFactory.class.php
> +                    // print_r($row);
no debug code in prs

2024-06-07 20:59 UTC, Aldus83 commented on src/modules/importfile/classes/Common/ImportFileFactory.class.php
> +                while (($row = fgetcsv($handle, 1000, ',')) !== false) {
as you mentoined in chat this might not work with large file sets and we might be looking  to use an ajax based batch - but for now might work if it imports whole file

2024-06-07 20:59 UTC, Aldus83 commented on src/modules/importfile/classes/Common/ImportFile.class.php
> +class ImportFile{
honestly I would prefer all this logic to be embedded in the existing file module

2024-06-10 07:38 UTC, MohamedTaha880 commented on src/modules/importfile/classes/Common/ImportFileFactory.class.php
> +                while (($row = fgetcsv($handle, 1000, ',')) !== false) {
Currently we have 331 lines in the file and they have all been imported

2024-06-10 08:26 UTC, merged