Validate shadows
quantacms/quanta pull request #378
Opened 2024-06-10 12:19 UTC by MohamedTaha880

2024-06-10 12:55 UTC, Aldus83 requested changes

2024-06-10 12:55 UTC, Aldus83 commented on src/modules/api/classes/Common/Api.class.php
> +    // Define the regex pattern for a strong password
@MohamedTaha880  this should be hookable, we can't impose this to all rpoducts

2024-06-10 12:55 UTC, Aldus83 commented on src/modules/node/classes/Common/NodeFactory.class.php
> +  public static function validateFormData(Environment $env, $full_form_data) {
@MohamedTaha880 this can't be implemented lke this, you can't implement a component's logic inside a Factory element. Each component should have it own validator. 
So you should just ask 

if ($form_item->validate() ...) 

and NOT copy pasting custom logic within this huge function

Please refactor accordingly

2024-06-11 13:59 UTC, Aldus83 requested changes

2024-06-11 13:59 UTC, Aldus83 commented on src/modules/shadow/assets/js/shadow.js
> +      form_items[fieldName] = perpearFormItem(inputField,newValue);
"perpear" is not a valid english work, makes reading code confusing

2024-06-11 13:59 UTC, Aldus83 commented on src/modules/form/classes/Qtags/FormItem.qtag.php
> +      $translated_text = \Quanta\Common\Localization::translatableText($this->env,'Questo campo è obbligatorio','required-error-message');
any reason for not using t?

2024-06-11 14:03 UTC, MohamedTaha880 commented on src/modules/form/classes/Qtags/FormItem.qtag.php
> +      $translated_text = \Quanta\Common\Localization::translatableText($this->env,'Questo campo è obbligatorio','required-error-message');
I didn't use t because it doesn't create nodes in _translations unlike translatableText
Which creates a node if it does not exist

2024-06-12 08:16 UTC, MohamedTaha880 commented on src/modules/form/classes/Qtags/FormItem.qtag.php
> +      $translated_text = \Quanta\Common\Localization::translatableText($this->env,'Questo campo è obbligatorio','required-error-message');
to make t function create nodes also we need to pass env to it
and we must change it in every place in the code

2024-06-12 13:16 UTC, merged