add map locale function
quantacms/quanta pull request #440
Opened 2024-08-20 10:30 UTC by MohamedTaha880

2024-08-21 17:26 UTC, Aldus83 requested changes

2024-08-21 17:26 UTC, Aldus83 commented on src/modules/localization/classes/Common/Localization.class.php
> +      'en' => 'en_US',
@MohamedTaha880 this hardcoded languages is a no-go.

languages are already present in _languages folder as nodes

just add a field into them to contain full locale
i.e. inside db/_languages/en/data.json you will have {... "locale_code":"en_US" ... }

2024-08-22 07:37 UTC, MohamedTaha880 commented on src/modules/localization/classes/Common/Localization.class.php
> +      'en' => 'en_US',
@Aldus83 Done

2024-08-22 14:47 UTC, Aldus83 requested changes

2024-08-22 14:47 UTC, Aldus83 commented on src/modules/localization/classes/Common/Localization.class.php
> +    $locale_code = 'it_IT';
default should not be it but  current language

2024-08-23 06:21 UTC, MohamedTaha880 commented on src/modules/localization/classes/Common/Localization.class.php
> +    $locale_code = 'it_IT';
@Aldus83 
the current language will be (it, en ....) not full locale code
So I put it_IT as default code if we can't find the locale code of the selected language

2024-08-23 09:56 UTC, merged